services:
  book-app:
    container_name: book-app-yotta
    build:
      context: .
    ports:
      - "8000:8000"
#    volumes:
#      - ./service:/service
    environment:
      DB_HOST: database
      DB_NAME: dbname
      DB_USER: db_user
      DB_PASS: pass
    depends_on:
      database:
        condition: service_healthy
    networks:
      - network_for_books
    command: python manage.py runserver 0.0.0.0:8000

  database:
    container_name: database-book-yotta
    image: postgres:latest
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    networks:
      - network_for_books
#    volumes:
#      - yotta_db_volume
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "db_user"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network_for_books:

#volumes:
#  yotta_db_volume:
#    name: yotta_db_volume
